/*******************************************************************************************************************************
*	
*	Filename: statemgr.c
*	Rev Date: 4/25/2012
*
*	File Description:
*			Application code to manage screen transitions
*
*******************************************************************************************************************************/

/*******************************************************************************************************************************
*			Include Files
*******************************************************************************************************************************/
#include "lpc_types.h"
#include "vardef.h"
#include "statemgr.h"
#include "statemgr_cfg.h"
#include "splash.h"
#include "pong.h"
#include "mainmenu.h"
#include "options.h"
#include "syscheck.h"


/*******************************************************************************************************************************
*			Macros
*******************************************************************************************************************************/
#define STATEMGR_C_VERSION_MAJOR			(1)
#define STATEMGR_C_VERSION_MINOR			(0)
#define STATEMGR_C_VERSION_PATCH			(0)


/*******************************************************************************************************************************
*			Static Variables
*******************************************************************************************************************************/
static T_EntryFsmFlg entryFsm;
static U1 ind_appscreen = i_SYS_SPLASH_SCREEN;    /* Index variable. Generated by HFSM Editor */
static U2 u2_s_splash_cntr;
static U1 u1_previous_state;
static U2 u2_s_state_cntr;


/*******************************************************************************************************************************
*			Static Function Prototypes
*******************************************************************************************************************************/
static void vd_s_AppStateMgrFSM(void);              /* Code for this function generated by HFSM Editor */


/*******************************************************************************************************************************
*			Function Definitions
*******************************************************************************************************************************/

/* Check version numbers */
#if(!((STATEMGR_C_VERSION_MAJOR == STATEMGR_H_VERSION_MAJOR) && (STATEMGR_C_VERSION_MAJOR == STATEMGR_CFG_H_VERSION_MAJOR)))
#error "Software Version Numbers do not match"
#endif

#if(!((STATEMGR_C_VERSION_MINOR == STATEMGR_H_VERSION_MINOR) && (STATEMGR_C_VERSION_MINOR == STATEMGR_CFG_H_VERSION_MINOR)))
#error "Software Version Numbers do not match"
#endif

#if(!((STATEMGR_C_VERSION_PATCH == STATEMGR_H_VERSION_PATCH) && (STATEMGR_C_VERSION_PATCH == STATEMGR_CFG_H_VERSION_PATCH)))
#error "Software Version Numbers do not match"
#endif


/*******************************************************************************************************************************
*	Function Name:			vd_g_AppStateMgrInitTask
*	Called By:				vd_g_AppInitTask
*	Timing:					Initialization
*	Description:			Initialize screen state
*
*******************************************************************************************************************************/
void vd_g_AppStateMgrInitTask(void)
{
    /* Initialization Code for state machine. Generated by HFSM */
    ind_appscreen = i_SYS_SPLASH_SCREEN; 
    entryFsm.flg = 0U;
    u1_previous_state = i_SYS_SPLASH_SCREEN;
    u2_s_splash_cntr = (U2)0;
    u2_s_state_cntr = (U2)0;
}


/*******************************************************************************************************************************
*	Function Name:			vd_g_AppStateMgrTask10ms
*	Called By:				vd_g_AppMgrTask10ms
*	Timing:					10 ms
*	Description:			Call functions to update screen states
*
*******************************************************************************************************************************/
void vd_g_AppStateMgrTask10ms(void)
{
    vd_s_AppStateMgrFSM();
}


/*******************************************************************************************************************************
*	Function Name:			vd_s_AppStateMgrFSM
*	Called By:				vd_g_AppStateMgrTask10ms
*	Timing:					10 ms
*	Description:			State Machine controller. Generated code via HFSM Editor
*
*******************************************************************************************************************************/
static void vd_s_AppStateMgrFSM(void)
{
    U1 u1_s_menu_select;

    switch(ind_appscreen)                           /* Next state analyser. */
    {
        case i_SYS_SPLASH_SCREEN:

            // Entry check
            if(!((U1)entryFsm.flg))
            {
                entryFsm.flg = (U1)1;
                vd_g_AppSplashInitTask();           /* Set up splash screen buffer */
            }

            // State actions (Moore).
            vd_g_AppSplashTask10ms();
            u2_s_splash_cntr++;                     /* Increment Counter - 5 Second Limit */

            // Next state selection.
            if(u2_s_splash_cntr >= (U2)SPLASH_SCRN_TMR_LIMIT)
            {
                vd_g_AppSplashExit();
                ind_appscreen = i_SYS_MAIN_MENU;
                entryFsm.flg = 0U;
            }
        break;

        case i_SYS_MAIN_MENU:

            // Entry check
            if(!((U1)entryFsm.flg))
            {
                entryFsm.flg = (U1)1;
                vd_g_AppMainMenuInitTask(); /* Call Main Menu Init Task */
                u2_s_state_cntr = (U2)0;
            }

            // State actions (Moore).
            vd_g_AppMainMenuTask10ms();     /* Call Update Task */

            if(u2_s_state_cntr < (U2)STATEMGR_INIT_THRESHOLD)
            {
                u2_s_state_cntr++;
            }

            // Next state selection.
            u1_s_menu_select = u1_g_AppMainMenuGetSelection();
            if(u2_s_state_cntr == (U2)STATEMGR_INIT_THRESHOLD)
            {
                if(u1_s_menu_select == STATEMGR_MM_PONG)
                {
                    vd_g_AppMainMenuExit();
                    ind_appscreen = i_SYS_PONG;
                    entryFsm.flg = 0U;
                }
                else if(u1_s_menu_select == STATEMGR_MM_SYSCHK)
                {
                    vd_g_AppMainMenuExit();
                    ind_appscreen = i_SYS_SYSCHECK;
                    entryFsm.flg = 0U;
                }
                else if(u1_s_menu_select == STATEMGR_MM_OPT)
                {	
                    vd_g_AppMainMenuExit();
                    ind_appscreen = i_SYS_OPTIONS;
                    u1_previous_state = i_SYS_MAIN_MENU;
                    entryFsm.flg = 0U;
                }
            }
        break;

        case i_SYS_PONG:

            // Entry check
            if(!((U1)entryFsm.flg))
            {
                entryFsm.flg = (U1)1;
                vd_g_AppPongInitTask();
                u2_s_state_cntr = (U2)0;
            }

            // State actions (Moore).
            vd_g_AppPongTask10ms();                         /* Update Pong Game */

            if(u2_s_state_cntr < (U2)STATEMGR_INIT_THRESHOLD)
            {
                u2_s_state_cntr++;
            }

            // Next state selection.
            if(u2_s_state_cntr >= (U2)STATEMGR_INIT_THRESHOLD)
            {
                u1_s_menu_select = u1_g_AppPongPause();
                if(u1_s_menu_select == STATEMGR_PONG_PAUSE)
                {
                    vd_g_AppPongStopSound();
                    ind_appscreen = i_SYS_OPTIONS;
                    u1_previous_state = i_SYS_PONG;
                    entryFsm.flg = 0U;
                }
            }
        break;

        case i_SYS_SYSCHECK:

            // Entry check
            if(!((U1)entryFsm.flg))
            {
                entryFsm.flg = (U1)1;
                vd_g_AppSysCheckInitTask();         /* Initialize System Check */
                u2_s_state_cntr = (U2)0;
            }

            // State actions (Moore).
            vd_g_AppSysCheckTask10ms();             /* Update SysCheck Screens */

            if(u2_s_state_cntr < (U2)STATEMGR_INIT_THRESHOLD)
            {
                u2_s_state_cntr++;
            }

            // Next state selection.
            if(u2_s_state_cntr >= (U2)STATEMGR_INIT_THRESHOLD)
            {
                u1_s_menu_select = u1_g_AppSysCheckPause();
                if(u1_s_menu_select == (U1)STATEMGR_SYSCHK_PAUSE)
                {
                    vd_g_AppSysCheckStopSound();
                    ind_appscreen = i_SYS_OPTIONS;
                    u1_previous_state = i_SYS_SYSCHECK;
                    entryFsm.flg = 0U;
                }
            }
        break;

        case i_SYS_OPTIONS:

            // Entry check
            if(!((U1)entryFsm.flg))
            {
                entryFsm.flg = (U1)1;
                vd_g_AppOptionsInitTask();          /* Initialize Options Menu */
                u2_s_state_cntr = (U2)0;
            }

            // State actions (Moore).
            vd_g_AppOptionsTask10ms();              /* Update Options Menu */

            if(u2_s_state_cntr < (U2)STATEMGR_INIT_THRESHOLD)
            {
                u2_s_state_cntr++;
            }

            // Next state selection.
            if(u2_s_state_cntr >= (U2)STATEMGR_INIT_THRESHOLD)
            {
                u1_s_menu_select = u1_g_AppOptionsGetSelection();
                if(u1_s_menu_select == (U1)STATEMGR_OPT_RTN)
                {	
                    vd_g_AppOptionsExit();
                    ind_appscreen = u1_previous_state;
                    entryFsm.flg = 0U;
                }
                else if(u1_s_menu_select == (U1)STATEMGR_OPT_MM)
                {	
                    vd_g_AppOptionsExit();
                    ind_appscreen = i_SYS_MAIN_MENU;
                    entryFsm.flg = 0U;
                }
            }
        break;
    }
}


/*******************************************************************************************************************************
*
*	Revisions:
*
*	Rev			Date			Author				Change Description
*	------		--------		----------			------------------------------
*	1.0.0		4/25/2012		J. Nabozny			Created
*
*******************************************************************************************************************************/

